name: Check if User is registered at jobsimulator.dev

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        status: [200]
    steps:
      - name: Set up environment variables
        env:
          USER_EMAIL: ${{ github.event.sender.email }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "USER_EMAIL=${USER_EMAIL}" >> $GITHUB_ENV
      - name: Call serverless endpoint
        if: ${{ matrix.status == 200 }}
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST -d "${USER_EMAIL}" https://jobsim-pr-user-check.deno.dev)
          if [ $status_code -ne 200 ]; then
            gh pr review ${{ github.event.number }} --body "User email ${USER_EMAIL} is not registered at jobsimulator.dev. Please make an account at https://www.jobsimulator.dev to have your PR be automatically tested."
            exit 1
          fi
